# Simply read a single PixC netcdf

In [1]:
import glob

from pixcdust.readers.netcdf import NcSimpleReader

In [2]:
swot_nc_files = glob.glob("/tmp/pixc/**/*.nc", recursive=True)

In [3]:
path = swot_nc_files[0]

# You can specify conditions on variables to filter data
conditions = {
    "sig0": {"operator": "gt", "threshold": 20},  # sig0 > 20
    "classification": {"operator": "ge", "threshold": 3},  # classification >= 3
}

ncsimple = NcSimpleReader(
    path, variables=["height", "sig0", "classification"], conditions=conditions
)

In [4]:
ncsimple.read()
ncsimple.data

<xarray.Dataset> Size: 2MB
Dimensions:         (points: 62404)
Coordinates:
  * points          (points) geometry 499kB POINT (0.7574284385788701 43.7710...
    latitude        (points) float64 499kB 43.77 43.77 43.86 ... 43.26 43.28
    longitude       (points) float64 499kB 0.7574 0.7629 1.242 ... 1.203 1.346
Data variables:
    height          (points) float32 250kB 237.8 238.1 138.8 ... 256.5 259.0
    sig0            (points) float32 250kB 171.5 135.6 37.29 ... 45.73 24.79
    classification  (points) float32 250kB 4.0 4.0 4.0 4.0 ... 3.0 6.0 6.0 3.0
Indexes:
    points   GeometryIndex (crs=EPSG:4326)
Attributes:
    description:                 cloud of geolocated interferogram pixels
    interferogram_size_azimuth:  3244
    interferogram_size_range:    4856
    looks_to_efflooks:           1.5337356015127879
    num_azimuth_looks:           7.0
    azimuth_offset:              6

In [5]:
# show some information
str_time_start, dt_time_start, cycle_number, pass_number, tile_number, swath_size = (
    ncsimple.extract_info_from_nc_attrs(path)
)
print(dt_time_start, cycle_number, pass_number, tile_number)

2023-04-07 07:36:56+00:00 483 16 78

## use data with xarray

In [6]:
ncsimple.to_xarray()  # same thing as ncsimple.data

<xarray.Dataset> Size: 2MB
Dimensions:         (points: 62404)
Coordinates:
  * points          (points) geometry 499kB POINT (0.7574284385788701 43.7710...
    latitude        (points) float64 499kB 43.77 43.77 43.86 ... 43.26 43.28
    longitude       (points) float64 499kB 0.7574 0.7629 1.242 ... 1.203 1.346
Data variables:
    height          (points) float32 250kB 237.8 238.1 138.8 ... 256.5 259.0
    sig0            (points) float32 250kB 171.5 135.6 37.29 ... 45.73 24.79
    classification  (points) float32 250kB 4.0 4.0 4.0 4.0 ... 3.0 6.0 6.0 3.0
Indexes:
    points   GeometryIndex (crs=EPSG:4326)
Attributes:
    description:                 cloud of geolocated interferogram pixels
    interferogram_size_azimuth:  3244
    interferogram_size_range:    4856
    looks_to_efflooks:           1.5337356015127879
    num_azimuth_looks:           7.0
    azimuth_offset:              6

## use data with pandas.dataframe

In [7]:
ncsimple.to_dataframe()

,height,sig0,classification,latitude,longitude
points,,,,,
POINT (0.75743 43.77104),237.767471,171.481934,4.0,43.771044,0.757428
POINT (0.76286 43.77205),238.144150,135.568436,4.0,43.772053,0.762864
POINT (1.24153 43.85973),138.818695,37.287514,4.0,43.859735,1.241529
POINT (1.24169 43.85976),138.812225,78.475822,4.0,43.859764,1.241692
POINT (1.24185 43.85979),138.757263,34.969410,4.0,43.859792,1.241845
...,...,...,...,...,...
POINT (1.07773 43.23586),306.179138,21.061779,3.0,43.235858,1.077728
POINT (1.15071 43.24922),279.771576,40.293037,3.0,43.249224,1.150710
POINT (1.19443 43.25721),266.089783,68.347923,6.0,43.257206,1.194433
POINT (1.20277 43.25873),256.502655,45.733727,6.0,43.258727,1.202775
POINT (1.34609 43.28475),259.012756,24.788414,3.0,43.284749,1.346095

## use data with geopandas.geodataframe

In [8]:
gdf = ncsimple.to_geodataframe()
gdf

,points,height,sig0,classification,latitude,longitude
0,POINT (0.75743 43.77104),237.767471,171.481934,4.0,43.771044,0.757428
1,POINT (0.76286 43.77205),238.144150,135.568436,4.0,43.772053,0.762864
2,POINT (1.24153 43.85973),138.818695,37.287514,4.0,43.859735,1.241529
3,POINT (1.24169 43.85976),138.812225,78.475822,4.0,43.859764,1.241692
4,POINT (1.24185 43.85979),138.757263,34.969410,4.0,43.859792,1.241845
...,...,...,...,...,...,...
62399,POINT (1.07773 43.23586),306.179138,21.061779,3.0,43.235858,1.077728
62400,POINT (1.15071 43.24922),279.771576,40.293037,3.0,43.249224,1.150710
62401,POINT (1.19443 43.25721),266.089783,68.347923,6.0,43.257206,1.194433
62402,POINT (1.20277 43.25873),256.502655,45.733727,6.0,43.258727,1.202775
62403,POINT (1.34609 43.28475),259.012756,24.788414,3.0,43.284749,1.346095